In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
df = pd.read_csv('/content/spam.csv', encoding="ISO-8859-1")
df.sample(7)

v1                                                 v2  \
985    ham  Carlos says he'll be at mu in  &lt;#&gt;  minutes   
3103   ham  That's y i said it's bad dat all e gals know u...   
2707  spam  Great NEW Offer - DOUBLE Mins & DOUBLE Txt on ...   
461    ham  Great. Never been better. Each day gives even ...   
1937   ham  The fact that you're cleaning shows you know w...   
4117   ham  Watch lor. I saw a few swatch one i thk quite ...   
1964   ham  Honeybee Said: *I'm d Sweetest in d World* God...   

                          Unnamed: 2 Unnamed: 3 Unnamed: 4  
985                              NaN        NaN        NaN  
3103                             NaN        NaN        NaN  
2707                             NaN        NaN        NaN  
461                              NaN        NaN        NaN  
1937  \" not \"what i need to do.\""        NaN        NaN  
4117                             NaN        NaN        NaN  
1964                             NaN        NaN        NaN

In [3]:
df = df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1)

In [4]:
df = df.rename(columns={'v1':'target','v2':'Mails'})


In [5]:
df.sample(7)

target                                              Mails
1738    ham                 K go and sleep well. Take rest:-).
642     ham               Probably gonna swing by in a wee bit
4014   spam  You will be receiving this week's Triple Echo ...
2514    ham      Ok ill send you with in  &lt;DECIMAL&gt;  ok.
1583    ham  It's cool, let me know before it kicks off aro...
629    spam  Todays Vodafone numbers ending with 4882 are s...
4911    ham                        I am on the way to tirupur.

In [6]:
df['target'].unique()

array(['ham', 'spam'], dtype=object)

In [7]:
df['target'] = df['target'].map({'ham':1 , 'spam':0}).astype(int)

In [8]:
df.sample(15)

target                                              Mails
218        1                   I have to take exam with march 3
4321       1  Sorry . I will be able to get to you. See you ...
2356       1                        No..he joined today itself.
1438       1                 Arms fine, how's Cardiff and uni? 
1507       1  Wen ur lovable bcums angry wid u, dnt take it ...
5325       1  Gal n boy walking in d park. gal-can i hold ur...
3681       1  Hello, hello, hi lou sorry it took so long 2 r...
4815       1  Anything is valuable in only 2 situations: Fir...
1202       1  Me also da, i feel yesterday night  wait til 2...
210        1  What's up bruv, hope you had a great break. Do...
3318       1                   Kay... Since we are out already 
3200       1                       Nice.nice.how is it working?
2071       1       Good night my dear.. Sleepwell&amp;Take care
5345       1                                  Wat Ì_ doing now?
5382       1  I can make it up there, squeezed  &lt;#&gt;  b...

In [9]:
df.shape

(5572, 2)

In [10]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
import nltk
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [13]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [14]:
from nltk.stem import WordNetLemmatizer
le = WordNetLemmatizer()
le.lemmatize('care')

'care'

In [15]:
text_cleaned_data = []

def clean_data(i,mode):
  if mode == 'train':
    text = i.lower() # lowering the data
    text = ''.join([j for j in text if j not in string.punctuation]) # remove punctuations
    text = ' '.join([k for k in text.split() if k not in stopwords.words('english')]) # remove stopwords
    text = ' '.join([le.lemmatize(p) for p in text.split()])
    text_cleaned_data.append(text)
  elif mode == 'inference':
    text = i.lower() # lowering the data
    text = ''.join([j for j in text if j not in string.punctuation]) # remove punctuations
    text = ' '.join([k for k in text.split() if k not in stopwords.words('english')]) # remove stopwords
    text = ' '.join([le.lemmatize(p) for p in text.split()])
    return text
  else:
    print('Please Pass Mode')

for i in df['Mails']:
  clean_data(i,'train')

In [16]:
# Before cleaning
df['Mails'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [17]:
text_cleaned_data[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

**Bag_of_words -> ML**

`Giving Independent data which is already cleaned to bag of words (so that it will convert into numbers) -> then give to ML `

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit(text_cleaned_data)
bow_res = cv.transform(text_cleaned_data).toarray()
bow_res

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
from sklearn.naive_bayes import GaussianNB
reg_bow = GaussianNB()
reg_bow.fit(bow_res,df['target'])

GaussianNB()

**Accuracy_BOW**

In [20]:
from sklearn.metrics import accuracy_score
print(f'Accuracy with BOW -> : {accuracy_score(df["target"],reg_bow.predict(bow_res))}')

Accuracy with BOW -> : 0.9388011486001435


In [21]:
import pickle
with open('BOW_ML.pkl','wb') as f:
  pickle.dump(reg_bow,f)

In [22]:
# Load file and do predictions

with open('/content/BOW_ML.pkl','rb') as f:
  model = pickle.load(f)


In [23]:
with open('BOW_CV.pkl','wb') as f:
  pickle.dump(cv,f)

In [24]:
with open('/content/BOW_CV.pkl','rb') as f:
  tonum = pickle.load(f)

In [25]:
# Testing:
import warnings
warnings.filterwarnings('ignore')

john_mail = 'I watched a Movie and it was really fantastic'

outcome_ = clean_data(john_mail,'inference')

input_ = tonum.transform([outcome_]).toarray()

r = model.predict(input_)[0]
if r == 1:
  print(f'John Main will come to Inbox ')
else:
  print(f'John Main will be in Spam Folder')

John Main will come to Inbox 


In [26]:
df['Mails'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [27]:
# Testing:
import warnings
warnings.filterwarnings('ignore')

john_mail = """Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.
Text FA to 87121 to
receive entry question(std txt rate)T&C's apply 08452810075over18's
"""

outcome_ = clean_data(john_mail,'inference')
print(outcome_)

input_ = tonum.transform([outcome_]).toarray()

r = model.predict(input_)[0]
if r == 1:
  print(f'John Main will come to Inbox ')
else:
  print(f'John Main will be in Spam Folder')

free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry questionstd txt ratetcs apply 08452810075over18s
John Main will be in Spam Folder


**TF_IDF -> ML**

`Giving Independent data which is already cleaned to TF_IDF (so that it will convert into numbers) -> then give to ML `

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tf.fit(text_cleaned_data)
tf_res = tf.transform(text_cleaned_data).toarray()
tf_res

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
from sklearn.naive_bayes import GaussianNB
tf_bow = GaussianNB()
tf_bow.fit(tf_res,df['target'])

GaussianNB()

**Accuracy_BOW**

In [30]:
from sklearn.metrics import accuracy_score
print(f'Accuracy with BOW -> : {accuracy_score(df["target"],tf_bow.predict(tf_res))}')

Accuracy with BOW -> : 0.9388011486001435


In [31]:
import pickle
with open('TF_ML.pkl','wb') as f:
  pickle.dump(tf_bow,f)

In [32]:
# Load file and do predictions

with open('/content/TF_ML.pkl','rb') as f:
  model = pickle.load(f)


In [33]:
with open('tf_CV.pkl','wb') as f:
  pickle.dump(tf,f)

In [34]:
with open('/content/tf_CV.pkl','rb') as f:
  tonum = pickle.load(f)

In [35]:
# Testing:
import warnings
warnings.filterwarnings('ignore')

john_mail = 'I watched a Movie and it was really fantastic'

outcome_ = clean_data(john_mail,'inference')

input_ = tonum.transform([outcome_]).toarray()

r = model.predict(input_)[0]
if r == 1:
  print(f'John Main will come to Inbox ')
else:
  print(f'John Main will be in Spam Folder')

John Main will come to Inbox 


In [36]:
df['Mails'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [37]:
# Testing:
import warnings
warnings.filterwarnings('ignore')

john_mail = """Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.
Text FA to 87121 to
receive entry question(std txt rate)T&C's apply 08452810075over18's
"""

outcome_ = clean_data(john_mail,'inference')
print(outcome_)

input_ = tonum.transform([outcome_]).toarray()

r = model.predict(input_)[0]
if r == 1:
  print(f'John Main will come to Inbox ')
else:
  print(f'John Main will be in Spam Folder')

free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry questionstd txt ratetcs apply 08452810075over18s
John Main will be in Spam Folder


**EMbedding -> ML**

In [38]:
c = []
for i in text_cleaned_data:
  c.append(len(i.split()))
print(max(c))

80


In [39]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [40]:
dic_size = 1000

result = [one_hot(j,dic_size) for j in text_cleaned_data]
data_input = pad_sequences(result,80,padding='post')
data_input

array([[403, 921, 256, ...,   0,   0,   0],
       [705, 235, 111, ...,   0,   0,   0],
       [351, 695, 275, ...,   0,   0,   0],
       ...,
       [914, 838, 295, ...,   0,   0,   0],
       [127, 853,  59, ...,   0,   0,   0],
       [441,  73, 267, ...,   0,   0,   0]], dtype=int32)

In [41]:
from sklearn.naive_bayes import GaussianNB
em_bow = GaussianNB()
em_bow.fit(data_input,df['target'])

GaussianNB()

**Accuracy_BOW**

In [42]:
from sklearn.metrics import accuracy_score
print(f'Accuracy with BOW -> : {accuracy_score(df["target"],em_bow.predict(data_input))}')

Accuracy with BOW -> : 0.14680545585068197


In [43]:
import pickle
with open('em_MOL.pkl','wb') as f:
  pickle.dump(em_bow,f)

In [44]:
# Load file and do predictions

with open('/content/em_MOL.pkl','rb') as f:
  model = pickle.load(f)


In [45]:
# Testing:
import warnings
warnings.filterwarnings('ignore')
dic_size=1000

john_mail = 'I watched a Movie and it was really fantastic'

outcome_ = clean_data(john_mail,'inference')
result = [one_hot(j,dic_size) for j in outcome_]
input_ = pad_sequences(result,80,padding='post')

r = model.predict(input_)[0]
if r == 1:
  print(f'John Main will come to Inbox ')
else:
  print(f'John Main will be in Spam Folder')

John Main will be in Spam Folder


In [46]:
df['Mails'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [47]:
# Testing:
import warnings
warnings.filterwarnings('ignore')

john_mail = """Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.
Text FA to 87121 to
receive entry question(std txt rate)T&C's apply 08452810075over18's
"""

outcome_ = clean_data(john_mail,'inference')

result = [one_hot(j,dic_size) for j in outcome_]
input_ = pad_sequences(result,80,padding='post')

r = model.predict(input_)[0]
if r == 1:
  print(f'John Main will come to Inbox ')
else:
  print(f'John Main will be in Spam Folder')

John Main will be in Spam Folder
